todoproj/todoproject/todoapp/urls.py
from django.urls import path

from todoapp import views

app_name = 'todoapp'
urlpatterns = [

    path('', views.index, name='index'),
    path('delete/<int:taskid>', views.delete, name='delete'),
    path('update/<int:id>', views.update, name='update'),
    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('dbvhome/<int:pk>/',views.Taskdetailview.as_view(),name='dbvhome'),
    path('cbvupdate/<int:pk>/',views.Taskupdateview.as_view(),name='cbvupdate'),
]

todoproj/todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproj/todoproject/todoapp/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority = models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.name

todoproj/todoproject/todoapp/forms.py
from .models import Task
from django import forms


class TodoForm(forms.ModelForm):
    class meta:
        model = Task
        fields = ['name', 'priority', 'date']

todoproj/todoproject/todoapp/views.py
import task1 as task1
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy

from todoapp.forms import TodoForm
from todoapp.models import Task
from django.views.generic import ListView, UpdateView
from django.views.generic.detail import DetailView


class Tasklistview(ListView):
    model = Task
    template_name = 'index.html'
    context_object_name = 'task1'


class Taskdetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'


class Taskupdateview(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('dbvhome', kwargs={'pk': self.object.id})


def index(request):
    task1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()

    return render(request, "index.html", {'task1': task1})


def delete(request, taskid):
    tas = Task.objects.get(id=taskid)
    if request.method == 'POST':
        tas.delete()
        return redirect('/')
    return render(request, "delete.html")


def update(request, id):
    task = Task.objects.get(id=id)
    f = TodoForm(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request, "edit.html", {'f': f, 'task': task})

todoproj/todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproj/todoproject/templates/delete.html
{% extends 'base.html'%}
{% block content %}

<form method="POST">
    {% csrf_token %}
    <h6>Did you complete this task??</h6>
    <button type="submit">confirm</button>

</form>

{% endblock %}

todoproj/todoproject/templates/detail.html
{% extends 'base.html' %}

{% block content %}

                <div class="shadow card">
                    <div class="card-body">
                        <h4 class="card-title">{{task.name}}</h4>
                        <p><b> {{task.priority}}</b></p>
                        <p><b> {{task.date}}</b></p>
                        <a href="" class="btn btn-danger">Done</a>
                        <a href="" class="btn btn-success">Update</a>
                    </div>
                </div>

{% endblock %}

todoproj/todoproject/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">confirm</button>

</form>

{% endblock %}

todoproj/todoproject/templates/index.html
{% extends 'base.html'%}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">


                <div class="banner-title">



                    <h2>ToDo</h2>
                </div>
            </div>
        </div>
    </div>

</div>



<div class="container">
    <div class="row">
        <div class="col-md-6">

<form method="POST" class="p-3 shadow">
    {% csrf_token %}
    <div class="form-group">
    <input type="text" class="form-control" placeholder="Enter your task" name="task">
    </div>
    <div class="form-group">
    <input type="text" class="form-control" placeholder="Enter your priority" name="priority">
    </div>
    <div class="form-group">
    <input type="date" class="form-control" placeholder="Enter your Date" name="date">
    </div>
    <input type="submit" class="btn btn-success">
</form>
        </div>




            <div class="col-md-6">

                {% for i in task1 %}<br>
                <div class="shadow card">
                    <div class="card-body">
                        <h4 class="card-title">{{i.name}}</h4>
                        <p><b> {{i.priority}}</b></p>
                        <p><b> {{i.date}}</b></p>
                        <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">Done</a>
                        <a href="{% url 'todoapp:update' i.id %}" class="btn btn-success">Update</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
</div>
{% endblock %}

todoproj/todoproject/templates/update.html
{% load static %}
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">confirm</button>
            </form>
        </div>
    </div>
</div>



{% endblock %}